# Generated by Django 2.0.1 on 2023-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_new_elo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='black_old_elo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='white_new_elo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='white_old_elo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
    ]
