# Generated by Django 2.0.1 on 2023-10-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_auto_20231012_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='new', max_length=200),
        ),
    ]
