# Generated by Django 2.0.1 on 2023-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0005_auto_20231020_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winrate',
            field=models.CharField(default='0%', max_length=200),
        ),
    ]
